<?php
class Zizelo_Test_Art extends Zizelo_Test_Abstract {
    public function setUp() {
        $this->addDocument(array('Зелёная весна', '青い春', 'aoi haru'));
        $this->addDocument(array('Конунг — человек с далёких островов', 'Kongen—Mannen fra utskjæret', 'kongen mannen fra utskjaeret'));
        $this->addDocument(array('Волшебная гора', 'Der Zauberberg', 'der zauberberg'));
        $this->addDocument(array('Бесстрашные убийцы вампиров', 'The Fearless Vampire Killers', 'Бал вампиров', 'the fearless vampire killers'));
        $this->addDocument(array('Разделяющий клин', '間の楔', 'ai no kusabi'));
        $this->addDocument(array('Футурама', 'Futurama', 'futurama'));
        $this->addDocument(array('Сталь остаётся', 'The Steel Remains', 'the steel remains'));
        $this->addDocument(array('Зов Ктулху', 'The Call of Cthulhu', 'the call of cthulhu movie'));
        $this->addDocument(array('Саус-Парк', 'South Park', 'Саут-Парк', 'Южный парк', 'south park'));
        $this->addDocument(array('Цветочный крест', 'tsvietochnyy kriest'));
        $this->addDocument(array('Еретики Дюны', 'Heretics of Dune', 'heretics of dune'));
        $this->addDocument(array('Здесь слышен океан', '海がきこえる', 'umi ga kikoeru'));
        $this->addDocument(array('Смерть в Венеции', 'Der Tod in Venedig', 'der tod in venedig'));
        $this->addDocument(array('Триллер', 'Thriller', 'thriller'));
        $this->addDocument(array('Уловка-22', 'Catch-22', 'catch 22'));
        $this->addDocument(array('Песня ветра и деревьев: санктус (стать святым)', '風と木の詩 SANCTUS -聖なるかな-', 'kaze to ki no uta sanctus sei naru kana'));
        $this->addDocument(array('Будь собой', 'Get Real', 'get real'));
        $this->addDocument(array('Рождественские голубые ели', 'Make the Yuletide Gay', 'make the yuletide gay'));
        $this->addDocument(array('Экс-предчувствие: шум', '予感EXノイズ', 'yokan ex noise'));
        $this->addDocument(array('Комедия', '喜劇', 'kigeki'));
        $this->addDocument(array('Табу', '御法度', 'gohatto'));
        $this->addDocument(array('Техану', 'Tehanu', 'tehanu'));
        $this->addDocument(array('На старт', 'On Your Mark', 'По твоему знаку', 'on your mark'));
        $this->addDocument(array('Суини Тодд, демон-парикмахер с Флит-стрит', 'Sweeney Todd: The Demon Barber of Fleet Street', 'sweeney todd the demon barber of fleet street'));
        $this->addDocument(array('(Прд.) До свидания, г-н Отчаяние!', '【俗・】さよなら絶望先生', 'zoku sayonara zetsubou sensei'));
        $this->addDocument(array('Странствующий Кэнсин: воспоминания', 'るろうに剣心 -明治剣客浪漫譚- 追憶編', 'rurouni kenshin tsuiokuhen'));
        $this->addDocument(array('Марс атакует!', 'Mars Attacks!', 'mars attacks'));
        $this->addDocument(array('Мутант', 'Mutant', 'mutant'));
        $this->addDocument(array('Евангелие нового времени: эйр/моё чистейшее сердце для тебя', '新世紀エヴァンゲリオン劇場版 Air/まごころを、君に', 'Конец Евангелиона', 'shin seiki evangerion gekijo ban air magokoro o kimi ni'));
        $this->addDocument(array('Евангелие нового времени: смерть и возрождение', '新世紀エヴァンゲリオン劇場版 シト新生', 'shin seiki evangerion gekijo ban shito shinsei'));
        $this->addDocument(array('Евангелие нового времени', '新世紀エヴァンゲリオン', 'neon genesis evangelion'));
        $this->addDocument(array('Чарли и шоколадная фабрика', 'Charlie and the Chocolate Factory', 'charlie and the chocolate factory'));
        $this->addDocument(array('Я люблю то, что я люблю, вот так!!', '好きなものは好きだからしょうがない!!', 'suki na mono wa suki dakara shouganai'));
        $this->addDocument(array('Лессон экс-экс', 'Lesson XX', 'lesson xx'));
        $this->addDocument(array('До свидания, г-н Отчаяние!', 'さよなら絶望先生', 'sayonara zetsubou sensei'));
        $this->addDocument(array('Фунты лиха в Париже и Лондоне', 'Down and Out in Paris and London', 'down and out in paris and london'));
        $this->addDocument(array('Билет в один конец', 'ぼくはこのまま帰らない', 'boku wa kono mama kaeranai'));
        $this->addDocument(array('Sex Pistols', 'sex pistols'));
        $this->addDocument(array('Эй, староста!', '生徒会長に忠告', 'seitokaichou ni chuukoku'));
        $this->addDocument(array('Тиран влюбляется', '恋する暴君', 'koi suru boukun'));
        $this->addDocument(array('Цитадель тьмы', 'The Citadel of Darkness', 'the citadel of darkness'));
        $this->addDocument(array('Гром на рассвете', 'Thunder in the Dawn', 'thunder in the dawn'));
        $this->addDocument(array('Наследие звёзд', 'A Heritage of Stars', 'a heritage of stars'));
        $this->addDocument(array('Блеск', 'Shine', 'shine'));
        $this->addDocument(array('Стуча в небесные врата', 'Knockin’ on Heaven’s Door', 'Достучаться до небес', 'knockin on heavens door'));
        $this->addDocument(array('Хогбены', 'The Hogbens', 'the hogbens'));
        $this->addDocument(array('Любовь начотдела', '課長の恋', 'kachou no koi'));
        $this->addDocument(array('Ночной поезд', 'Night Train', 'night train 2009'));
        $this->addDocument(array('Тысяча девятьсот восемьдесят четвёртый', 'Nineteen Eighty-Four', '1984', 'nineteen eighty four'));
        $this->addDocument(array('Девичья роза', '百日の薔薇', 'hyakujitsu no bara'));
        $this->addDocument(array('Пипец', 'Kick-Ass', 'kick ass'));
        $this->addDocument(array('Взлететь', 'The Hurt Locker', 'Повелитель бури', 'the hurt locker'));
        $this->addDocument(array('Приключения Вернера Хольта', 'Die Abenteuer des Werner Holt', 'die abenteuer des werner holt'));
        $this->addDocument(array('Милосердие', 'milosierdiye'));
        $this->addDocument(array('Узелок на память', 'Memento', 'Помни', 'memento'));
        $this->addDocument(array('Каппа', '河童', 'В стране водяных', 'kappa'));
        $this->addDocument(array('Нулевой километр', 'nulievoy kilomietr'));
        $this->addDocument(array('Робокоп-2', 'RoboCop 2', 'robocop 2'));
        $this->addDocument(array('Похороните меня за плинтусом', 'pokhoronitie mienia za plintusom'));
        $this->addDocument(array('Процесс', 'Der Prozess', 'der prozess'));
        $this->addDocument(array('Робокоп', 'RoboCop', 'Робот-полицейский', 'robocop'));
        $this->addDocument(array('Дети наших детей', 'Our Children’s Children', 'our childrens children'));
        $this->addDocument(array('Папа и море', 'Pappan och havet', 'Муми-папа и море', 'pappan och havet'));
        $this->addDocument(array('300', '300 спартанцев', '300'));
        $this->addDocument(array('Линия красоты', 'The Line of Beauty', 'the line of beauty'));
        $this->addDocument(array('Gravitation: Lyrics of Love', 'gravitation lyrics of love'));
        $this->addDocument(array('Наёмный убийца', 'Hitman', 'Хитман', 'Хитмэн', 'hitman'));
        $this->addDocument(array('Человек-ящик', '箱男', 'hako otoko'));
        $this->addDocument(array('Три миллиона оставленных в покое', 'rvanaya grielka 18'));
        $this->addDocument(array('Воображариум доктора Парнаса', 'The Imaginarium of Doctor Parnassus', 'the imaginarium of doctor parnassus'));
        $this->addDocument(array('Движущиеся картинки', 'Moving Pictures', 'moving pictures'));
        $this->addDocument(array('Принц Госплана', 'prints gosplana'));
        $this->addDocument(array('Пинк Флойд Стена', 'Pink Floyd The Wall', 'pink floyd the wall'));
        $this->addDocument(array('Эрик', 'Eric', 'Эрик, а также Ночная стража, ведьмы и Коэн-Варвар', 'eric'));
        $this->addDocument(array('Канон', 'カノン', 'kanon 2006'));
        $this->addDocument(array('По ту сторону', 'Auf der anderen Seite', 'Yaşamın Kıyısında', 'На краю рая', 'auf der anderen seite'));
        $this->addDocument(array('Стража! Стража!', 'Guards! Guards!', 'guards guards'));
        $this->addDocument(array('Последний король Шотландии', 'The Last King of Scotland', 'the last king of scotland'));
        $this->addDocument(array('Воин и императрица', 'Der Krieger und die Kaiserin', 'Принцесса и воин', 'der krieger und die kaiserin'));
        $this->addDocument(array('Горец II: Оживление', 'Highlander II: The Quickening', 'highlander 2'));
        $this->addDocument(array('Шоковая подружка', '電波的な彼女', 'denpa teki na kanojo'));
        $this->addDocument(array('Русский меч', 'russkiy miech'));
        $this->addDocument(array('Жажда', 'zhazhda'));
        $this->addDocument(array('Парижская любовь', 'Паризьке кохання', 'paryzke kokhannia'));
        $this->addDocument(array('Классические истории', '青い文学シリーズ', 'aoi bungaku series'));
        $this->addDocument(array('Гремлины-2: Новая порция', 'Gremlins 2: The New Batch', 'gremlins 2'));
        $this->addDocument(array('Чистая романтика', '純情ロマンチカ', 'junjou romantica'));
        $this->addDocument(array('Бог-Император Дюны', 'God Emperor of Dune', 'god emperor of dune'));
        $this->addDocument(array('Вандэфул дэйз', '원 더풀 데이즈', 'Фантастические дни', 'wondeopul deijeu'));
        $this->addDocument(array('Да Капо иф', 'ダ・カーポ イフ', 'da capo if'));
        $this->addDocument(array('Каллиграф', '書家', 'shoka'));
        $this->addDocument(array('Аватар', 'Avatar', 'avatar'));
        $this->addDocument(array('Рейд на Энтеббе', 'Raid on Entebbe', 'raid on entebbe'));
        $this->addDocument(array('Кошачья благодарность', '猫の恩返し', 'Возвращение кота', 'neko no ongaeshi'));
        $this->addDocument(array('Кошмар перед Рождеством', 'The Nightmare Before Christmas', 'the nightmare before christmas'));
        $this->addDocument(array('Похождения Геда', 'ゲド戦記', 'Сказания Земноморья', 'gedo senki'));
        $this->addDocument(array('Молодой Тёрлес', 'Der junge Törless', 'der junge torless'));
        $this->addDocument(array('Ахиллес и черепаха', 'アキレスと亀', 'akiresu to kame'));
        $this->addDocument(array('Горец', 'Highlander', 'highlander'));
        $this->addDocument(array('Алиса в Стране чудес', 'Alice in Wonderland', 'alice in wonderland'));
        $this->addDocument(array('Река утопленников', 'A River Made to Drown in', 'a river made to drown in'));
        $this->addDocument(array('Могила светлячков', '火垂るの墓', 'hotaru no haka'));
        $this->addDocument(array('С.-Л.-С. панк!', 'SLC Punk!', 'Панк из Солт-Лейк-Сити', 'Панки из Солт-Лэйк сити', 'pank iz solt lieyk siti'));
        $this->addDocument(array('Падение', 'The Fall', 'Запределье', 'the fall'));
        $this->addDocument(array('Дикий, дикий Вест', 'Wild Wild West', 'Дикий, дикий Запад', 'wild wild west'));
        $this->addDocument(array('71 фрагмент хронологии случая', '71 Fragmente einer Chronologie des Zufalls', '71 fragmente einer chronologie des zufalls'));
        $this->addDocument(array('Милые кости', 'The Lovely Bones', 'the lovely bones'));
        $this->addDocument(array('5 сантиметров в секунду: э чеин оф шорт сториз эбаут зэа дистанс', '秒速５センチメートルアチェインオブショートストリーズアバウトゼアディスタンス', '5 сантиметров в секунду: цепь историй об их отдалённости', 'Пять сантиметров в секунду', 'byosoku 5 senchimetoru'));
        $this->addDocument(array('Королевская битва', 'バトル・ロワイアル', 'batoru rowaiaru'));
        $this->addDocument(array('Волшебник поневоле', 'volshebnik ponievolie'));
        $this->addDocument(array('Крабат', 'Krabat', 'Крабат. Ученик колдуна', 'krabat'));
        $this->addDocument(array('Понё на утёсе', '崖の上のポニョ', 'Рыбка Поньо', 'Рыбка Поньо на утёсе', 'gake no ue no ponyo'));
        $this->addDocument(array('Поход изгоя', 'Exile’s Quest', 'Поход изгоев', 'exiles quest'));
        $this->addDocument(array('Движущийся замок Хаула', 'ハウルの動く城', 'Ходячий замок', 'hauru no ugoku shiro'));
        $this->addDocument(array('Сэн: Тихиро, унесённая духами', '千と千尋の神隠し', 'Унесённые призраками', 'sen to chihiro no kamikakushi'));
        $this->addDocument(array('Принцесса-дух', 'もののけ姫', 'Принцесса Мононокэ', 'mononoke hime'));
        $this->addDocument(array('Красная свинья', '紅の豚', 'Порко Россо', 'kurenai no buta'));
        $this->addDocument(array('Ведьмина служба доставки', '魔女の宅急便', 'majo no takkyubin'));
        $this->addDocument(array('Мой сосед Тоторо', 'となりのトトロ', 'tonari no totoro'));
        $this->addDocument(array('Почти невероятное убийство', 'pochti nievieroyatnoye ubiystvo'));
        $this->addDocument(array('Небесный замок Лапута', '天空の城ラピュタ', 'tenku no shiro rapyuta'));
        $this->addDocument(array('Семь следов на пути к Сатане', 'Seven Footprints to Satan', 'Семь шагов к Сатане', 'seven footprints to satan'));
        $this->addDocument(array('Навсикая из долины Ветра', '風の谷のナウシカ', 'kaze no tani no naushika'));
        $this->addDocument(array('Семь гномов — в лесу одни мужчины', '7 Zwerge – Männer allein im Wald', '7 zwerge manner allein im wald'));
        $this->addDocument(array('Нелюбимый', 'Loveless', 'loveless'));
        $this->addDocument(array('Эльфийская песнь', 'Elfen Lied', 'Эльфийская ложь', 'エルフェンリート', 'elfen lied'));
        $this->addDocument(array('137 секунд', '137 sekund', '137 sekund'));
        $this->addDocument(array('Рваный край', 'A Wrinkle in the Skin', 'The Ragged Edge', 'Складка кожи', 'a wrinkle in the skin'));
        $this->addDocument(array('Безславные ублютки', 'Inglourious Basterds', 'Бесславные ублюдки', 'inglourious basterds'));
        $this->addDocument(array('Возвращение Красной Шапочки', 'vozvrascheniye krasnoy shapochki'));
        $this->addDocument(array('Камин-аут', 'Coming Out', 'coming out'));
        $this->addDocument(array('Летний шторм', 'Sommersturm', 'sommersturm'));
        $this->addDocument(array('Двойное отражение или Эпизоды иной жизни Александра Грибоедова', 'dvoynoye otrazheniye'));
        $this->addDocument(array('Шерлок Холмс', 'Sherlock Holmes', 'sherlock holmes'));
        $this->addDocument(array('Золотые годы Крысы из нержавеющей стали', 'The Golden Years of the Stainless Steel Rat', 'Золотые годы Стальной Крысы', 'the golden years of the stainless steel rat'));
        $this->addDocument(array('Мужики, которые таращатся на коз', 'The Men Who Stare at Goats', 'Безумный спецназ', 'the men who stare at goats'));
        $this->addDocument(array('Вещие сёстры', 'Wyrd Sisters', 'wyrd sisters'));
        $this->addDocument(array('Чародей', 'Dwa światy', 'Spellbinder', 'spellbinder'));
        $this->addDocument(array('Берсерк', 'Berserk', 'ベルセルク剣風伝奇', 'berserk'));
        $this->addDocument(array('Пропавшие', 'Lost', 'Остаться в живых', 'lost'));
        $this->addDocument(array('Вскруджило', 'Scrooged', 'Новая рождественская сказка', 'scrooged'));
        $this->addDocument(array('Морт', 'Mort', 'Мор, ученик Смерти', 'mort'));
        $this->addDocument(array('Свет фантастический', 'The Light Fantastic', 'Безумная звезда', 'the light fantastic'));
        $this->addDocument(array('Из России с любовью', 'From Russia with Love', 'from russia with love'));
        $this->addDocument(array('Коробка', 'The Box', 'Посылка', 'the box'));
        $this->addDocument(array('2012', '2012'));
        $this->addDocument(array('Куроцука', '黒塚', 'Куродзука', 'kurozuka'));
        $this->addDocument(array('Луна', 'Moon', 'Луна 2112', 'moon'));
        $this->addDocument(array('Пираты Карибского моря: Проклятие „Чёрной жемчужины“', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'the curse of the black pearl'));
        $this->addDocument(array('Хороший, плохой, странный', '좋은 놈, 나쁜 놈, 이상한 놈', 'joheunnom nabbeunnom isanghannom'));
        $this->addDocument(array('Вальс с Баширом', 'ואלס עם באשיר', 'vals im bashir'));
        $this->addDocument(array('Животноводческая ферма (сказка)', 'Animal Farm: A Fairy Story', 'Скотный двор', 'animal farm'));
        $this->addDocument(array('Друзья Питера', 'Peter’s Friends', 'peters friends'));
        $this->addDocument(array('Мертвец', 'Dead Man', 'dead man'));
        $this->addDocument(array('Буги-ночи', 'Boogie Nights', 'Ночи в стиле буги', 'boogie nights'));
        $this->addDocument(array('Жили-были в Америке', 'Once Upon a Time in America', 'Однажды в Америке', 'once upon a time in america'));
        $this->addDocument(array('Магнолия', 'Magnolia', 'magnolia'));
        $this->addDocument(array('Макс Пэйн', 'Max Payne', 'max payne film'));
        $this->addDocument(array('Вечное сияние чистого разума', 'Eternal Sunshine of the Spotless Mind', 'eternal sunshine of the spotless mind'));
        $this->addDocument(array('Лола бежит', 'Lola rennt', 'Беги, Лола, беги', 'lola rennt'));
        $this->addDocument(array('Смертенепроницаемая', 'Death Proof', 'Доказательство смерти', 'death proof'));
        $this->addDocument(array('Планетарный ужас', 'Planet Terror', 'Планета страха', 'planet terror'));
        $this->addDocument(array('Зелёная миля', 'The Green Mile', 'the green mile'));
        $this->addDocument(array('Тёмный рыцарь', 'The Dark Knight', 'the dark knight'));
        $this->addDocument(array('УОЛЛ•И', 'WALL•E', 'ВАЛЛ•И', 'wall e'));
        $this->addDocument(array('Кунфуйская панда', 'Kung Fu Panda', 'Кунг-Фу Панда', 'kung fu panda'));
        $this->addDocument(array('Хроники Нарнии: Принц Каспиан', 'The Chronicles of Narnia: Prince Caspian', 'the chronicles of narnia prince caspian'));
        $this->addDocument(array('Звёздная пыль', 'Stardust', 'stardust'));
        $this->addDocument(array('Властелин колец: Возвращение короля', 'The Lord of the Rings: The Return of the King', 'the return of the king'));
        $this->addDocument(array('Солги мне', 'Lie to Me', 'Обмани меня', 'Теория лжи', 'lie to me'));
        $this->addDocument(array('Физика или химия', 'Física o Química', 'fisica o quimica'));
        $this->addDocument(array('Китаро с кладбища', '墓場鬼太郎', 'hakaba kitarou'));
        $this->addDocument(array('Хеталия эксис пауэрз', 'ヘタリア Axis Powers', 'Хеталия и страны Оси', 'hetaria axis powers'));
        $this->addDocument(array('Чёрная метка', 'Burn Notice', 'Срочное уведомление', 'burn notice'));
        $this->addDocument(array('Манускрипт ниндзя', '獣兵衛忍風帖', 'jubei ninpucho'));
        $this->addDocument(array('Зов Ктулху', 'The Call of Cthulhu', 'the call of cthulhu'));
        $this->addDocument(array('Взвод', 'Platoon', 'platoon'));
        $this->addDocument(array('Лучшее время года', 'Vintage Season', 'vintage season'));
        $this->addDocument(array('Тёмный мир', 'The Dark World', 'the dark world'));
        $this->addDocument(array('Ярость', 'Fury', 'fury'));
        $this->addDocument(array('КОМА', 'koma'));
        $this->addDocument(array('Ливан', 'לבנון', 'lebanon'));
        $this->addDocument(array('Невидимка', 'Hollow Man', 'hollow man'));
        $this->addDocument(array('Мистер Никто', 'Mr. Nobody', 'mr nobody'));
        $this->addDocument(array('Up', 'up'));
        $this->addDocument(array('La habitación de Fermat', 'la habitacion de fermat'));
        $this->addDocument(array('Робин Гуд', 'Robin Hood', 'robin hood'));
        $this->addDocument(array('One Flew over the Cuckoo’s Nest', 'Пролетая над гнездом кукушки', 'one flew over the cuckoos nest'));
        $this->addDocument(array('Превращение', 'Die Verwandlung', 'die verwandlung'));
        $this->addDocument(array('Лев, колдунья и платяной шкаф', 'The Lion, the Witch and the Wardrobe', 'the lion the witch and the wardrobe'));
        $this->addDocument(array('Маршалы Объединённых Государств', 'U.S. Marshals', 'Служители закона', 'Судебные исполнители', 'us marshals'));
        $this->addDocument(array('Люди в чёрном 2', 'Men in Black II', 'men in black 2'));
        $this->addDocument(array('Матрица революционирует', 'The Matrix Revolutions', 'Матрица: Революция', 'the matrix revolutions'));
        $this->addDocument(array('Матрица перезагружена', 'The Matrix Reloaded', 'Матрица: Перезагрузка', 'the matrix reloaded'));
        $this->addDocument(array('Матрица', 'The Matrix', 'the matrix'));
        $this->addDocument(array('Четверг', 'Thursday', 'Кровавый четверг', 'thursday'));
        $this->addDocument(array('Назад в будущее: часть 3', 'Back to the Future Part III', 'back to the future 3'));
        $this->addDocument(array('Назад в будущее: часть 2', 'Back to the Future Part II', 'back to the future 2'));
        $this->addDocument(array('Назад в будущее', 'Back to the Future', 'back to the future 1'));
        $this->addDocument(array('Трасса 60', 'Interstate 60', 'interstate 60'));
        $this->addDocument(array('Хороший, плохой, злой', 'Il buono, il brutto, il cattivo', 'il buono il brutto il cattivo'));
        $this->addDocument(array('Дэс ноут', 'デスノート', 'Тетрадь смерти', 'death note'));
        $this->addDocument(array('Разрушители мифов', 'Mythbusters', 'Разрушители легенд', 'mythbusters'));
        $this->addDocument(array('Маёр Пэйн', 'Major Payne', 'major payne'));
        $this->addDocument(array('Кольцо вокруг Солнца', 'Ring around the Sun', 'ring around the sun'));
        $this->addDocument(array('Заповедник гоблинов', 'The Goblin Reservation', 'the goblin reservation'));
        $this->addDocument(array('Операция „Антиирод“', 'opieratsiya antiirod'));
        $this->addDocument(array('Один на один', 'odin na odin'));
        $this->addDocument(array('Посредник', 'posriednik'));
        $this->addDocument(array('Тёрн', 'tiorn'));
        $this->addDocument(array('Череп в небесах', 'chieriep v niebiesakh'));
        $this->addDocument(array('Череп на рукаве', 'chieriep na rukavie'));
        $this->addDocument(array('Вернуть посох', 'viernut posokh'));
        $this->addDocument(array('Дочь некроманта', 'doch niekromanta'));
        $this->addDocument(array('Война мага', 'voyna maga'));
        $this->addDocument(array('Одиночество мага', 'odinochiestvo maga'));
        $this->addDocument(array('Странствия мага', 'stranstviya maga'));
        $this->addDocument(array('Рождение мага', 'rozhdieniye maga'));
        $this->addDocument(array('Гибель богов', 'gibiel bogov'));
        $this->addDocument(array('Адамант Хенны', 'adamant khienny'));
        $this->addDocument(array('Чёрное копьё', 'chiornoye kopiyo'));
        $this->addDocument(array('Эльфийский клинок', 'elfiyskiy klinok'));
        $this->addDocument(array('Пьяная ночь в весеннем бризе', '春风沉醉的晚上', 'Весенняя лихорадка', 'chun feng chen zui de ye wan'));
        $this->addDocument(array('А-ба-ба-ба-ба', 'あばばばば', 'a ba ba ba ba'));
        $this->addDocument(array('Сонная лощина', 'Sleepy Hollow', 'sleepy hollow'));
        $this->addDocument(array('Невеста-труп', 'Corpse Bride', 'Труп невесты', 'corpse bride'));
        $this->addDocument(array('Крупная рыба', 'Big Fish', 'big fish'));
        $this->addDocument(array('Эд Вуд', 'Ed Wood', 'ed wood'));
        $this->addDocument(array('Бэтмен возвращается', 'Batman Returns', 'batman returns'));
        $this->addDocument(array('Эдвард — руки-ножницы', 'Edward Scissorhands', 'edward scissorhands'));
        $this->addDocument(array('Бэтмен', 'Batman', 'batman'));
        $this->addDocument(array('Битлджус', 'Beetlejuice', 'beetlejuice'));
        $this->addDocument(array('Большое приключение Пи-Ви', 'Pee-wee’s Big Adventure', 'pee wees big adventure'));
        $this->addDocument(array('Звонок', 'The Ring', 'the ring'));
        $this->addDocument(array('Крикуны', 'Screamers', 'screamers'));
        $this->addDocument(array('Жили-были в Мексике', 'Once Upon a Time in Mexico', 'Однажды в Мексике', 'once upon a time in mexico'));
        $this->addDocument(array('Музыкант', 'El Mariachi', 'el mariachi'));
        $this->addDocument(array('Джуманджи', 'Jumanji', 'jumanji'));
        $this->addDocument(array('Вход и выход', 'In & Out', 'in and out'));
        $this->addDocument(array('Самый дальний берег', 'The Farthest Shore', 'На последнем берегу', 'the farthest shore'));
        $this->addDocument(array('Другой ветер', 'The Other Wind', 'На иных ветрах', 'the other wind'));
        $this->addDocument(array('Сказания Земноморья', 'Tales from Earthsea', 'tales from earthsea'));
        $this->addDocument(array('Гробницы Атуана', 'The Tombs of Atuan', 'the tombs of atuan'));
        $this->addDocument(array('Волшебник Земноморья', 'A Wizard of Earthsea', 'a wizard of earthsea'));
        $this->addDocument(array('Леон', 'Léon', 'leon'));
        $this->addDocument(array('Звёздные войны. Эпизод VI: Возвращение джедая', 'Star Wars Episode VI: Return of the Jedi', 'star wars 6'));
        $this->addDocument(array('Звёздные войны. Эпизод V: Империя наносит ответный удар', 'Star Wars Episode V: The Empire Strikes Back', 'star wars 5'));
        $this->addDocument(array('Звёздные войны. Эпизод III: Месть сита', 'Star Wars Episode III: Revenge of the Sith', 'Звёздные войны. Эпизод III: Месть ситхов', 'star wars 3'));
        $this->addDocument(array('Звёздные войны. Эпизод II: Атака клонов', 'Star Wars Episode II: Attack of the Clones', 'star wars 2'));
        $this->addDocument(array('Звёздные войны. Эпизод I: Скрытая угроза', 'Star Wars Episode I: The Phantom Menace', 'star wars 1'));
        $this->addDocument(array('Звёздные войны. Эпизод IV: Новая надежда', 'Star Wars Episode IV: A New Hope', 'star wars 4'));
        $this->addDocument(array('АО „Монстры“', 'Monsters, Inc.', 'Корпорация монстров', 'monsters inc'));
        $this->addDocument(array('Отчаянный', 'Desperado', 'desperado'));
        $this->addDocument(array('Властелин колец: Две башни', 'The Lord of the Rings: The Two Towers', 'Властелин колец: Две крепости', 'the two towers'));
        $this->addDocument(array('Властелин колец: Братство Кольца', 'The Lord of the Rings: The Fellowship of the Ring', 'the fellowship of the ring'));
        $this->addDocument(array('Сильмариллион', 'The Silmarillion', 'the silmarillion'));
        $this->addDocument(array('Хоббит, или Туда и обратно', 'The Hobbit, or There and Back Again', 'the hobbit'));
        $this->addDocument(array('Властелин колец', 'The Lord of the Rings', 'the lord of the rings'));
        $this->addDocument(array('Сквозь зеркало, и что там увидела Алиса', 'Through the Looking-Glass, and What Alice Found There', 'Алиса в Зазеркалье', 'through the looking glass'));
        $this->addDocument(array('Приключения Алисы в Стране чудес', 'Alice’s Adventures in Wonderland', 'alices adventures in wonderland'));
        $this->addDocument(array('Горбатая гора', 'Brokeback Mountain', 'brokeback mountain'));
        $this->addDocument(array('Догма', 'Dogma', 'dogma'));
        $this->addDocument(array('Соседка', 'The Girl Next Door', 'the girl next door'));
        $this->addDocument(array('Слевин — счастливый номер', 'Lucky Number Slevin', 'Счастливое число Слевина', 'lucky number slevin'));
        $this->addDocument(array('Пятый элемент', 'The Fifth Element', 'the fifth element'));
        $this->addDocument(array('Четыре комнаты', 'Four Rooms', 'four rooms'));
        $this->addDocument(array('День независимости', 'Independence Day', 'independence day'));
        $this->addDocument(array('Люди в чёрном', 'Men in Black', 'men in black'));
        $this->addDocument(array('Грешный город', 'Sin City', 'Город грехов', 'sin city'));
        $this->addDocument(array('День сурка', 'Groundhog Day', 'groundhog day'));
        $this->addDocument(array('Симпсоны', 'The Simpsons', 'the simpsons'));
        $this->addDocument(array('Семь самураев', '七人の侍', 'shichinin no samurai'));
        $this->addDocument(array('Сёгун', 'Shōgun', 'shogun'));
        $this->addDocument(array('Урвать.', 'Snatch.', 'Большой куш', 'Спиздили', 'snatch'));
        $this->addDocument(array('Выдали со всеми потрохами', 'Lock, Stock and Two Smoking Barrels', 'Карты, деньги, два ствола', 'lock stock and two smoking barrels'));
        $this->addDocument(array('Бульварное чтиво', 'Pulp Fiction', 'Криминальное чтиво', 'pulp fiction'));
        $this->addDocument(array('Крепкий орешек-2: Ещё крепче', 'Die Hard 2: Die Harder', 'die hard 2 die harder'));
        $this->addDocument(array('Крепкий орешек', 'Die Hard', 'die hard'));
        $this->addDocument(array('Небесный капитан и мир будущего', 'Sky Captain and the World of Tomorrow', 'sky captain and the world of tomorrow'));
        $this->addDocument(array('Красный мент', 'Red Heat', 'Красная жара', 'red heat'));
        $this->addDocument(array('Убить Билла', 'Kill Bill', 'kill bill'));
        $this->addDocument(array('Бегущий по лезвию', 'Blade Runner', 'blade runner'));
        $this->addDocument(array('Чужой', 'Alien', 'alien'));
        $this->addDocument(array('Хищник', 'Predator', 'predator'));
        $this->addDocument(array('Коммандо', 'Commando', 'commando'));
        $this->addDocument(array('Каратель', 'The Punisher', 'the punisher'));
        $this->addDocument(array('Армагеддон', 'Armageddon', 'armageddon'));
        $this->addDocument(array('Халк', 'Hulk', 'hulk'));
        $this->addDocument(array('Вольная птица — крепкий орешек', 'Live Free or Die Hard', 'live free or die hard'));
        $this->addDocument(array('Судья Дрэдд', 'Judge Dredd', 'judge dredd'));
        $this->addDocument(array('Терминатор-2: Судный день', 'Terminator 2: Judgment Day', 'terminator 2 judgment day'));
        $this->addDocument(array('Бездна', 'The Abyss', 'the abyss'));
        $this->addDocument(array('Чужие', 'Aliens', 'aliens'));
        $this->addDocument(array('Терминатор', 'The Terminator', 'the terminator'));
        $this->addDocument(array('Chapterhouse: Dune', 'chapterhouse dune'));
        $this->addDocument(array('Дети Дюны', 'Children of Dune', 'children of dune'));
        $this->addDocument(array('Мессия Дюны', 'Dune Messiah', 'dune messiah'));
        $this->addDocument(array('Дюна', 'Dune', 'dune'));
        $this->addDocument(array('Гремлины', 'Gremlins', 'gremlins'));
        $this->addDocument(array('Хаус', 'House', 'house'));
        $this->addDocument(array('Коралина', 'Coraline', 'Коралина в Стране Кошмаров', 'coraline'));
        $this->addDocument(array('Живые мысли', 'zhivyye mysli'));
        $this->addDocument(array('Книга пророка Иезекииля', 'book of ezekiel'));
        $this->addDocument(array('Семиосфера', 'semiosphere'));
        $this->addDocument(array('Критика чистого разума', 'Kritik der reinen Vernunft', 'kritik der reinen vernunft'));
        $this->addDocument(array('Теория Большого взрыва', 'The Big Bang Theory', 'the big bang theory'));
        $this->addDocument(array('Палата № 6', 'palata 6'));
        $this->addDocument(array('Пирамиды', 'Pyramids', 'pyramids'));
        $this->addDocument(array('Изведовство', 'Sourcery', 'Посох и шляпа', 'sourcery'));
        $this->addDocument(array('Равночинцы', 'Equal Rites', 'Творцы заклинаний', 'equal rites'));
        $this->addDocument(array('Цвет волшебства', 'The Colour of Magic', 'the colour of magic'));
        $this->addDocument(array('Терри Пратчетт', 'Terry Pratchett', 'terry pratchett'));
        $this->addDocument(array('Ян Флеминг', 'Ian Fleming', 'Йен Флеминг', 'ian fleming'));
        $this->addDocument(array('Билл Мюррэй', 'Bill Murray', 'Билл Мюррей', 'bill murray'));
        $this->addDocument(array('Ричард Доннер', 'Richard Donner', 'richard donner'));
        $this->addDocument(array('Джеймс Кэмерон', 'James Cameron', 'james cameron'));
        $this->addDocument(array('Сигурни Уивер', 'Sigourney Weaver', 'sigourney weaver'));
        $this->addDocument(array('Зои Салданья', 'Zoe Saldaña', 'Зоя Салдана', 'Зоя Салданья', 'zoe saldana'));
        $this->addDocument(array('Мишель Родригес', 'Michelle Rodriguez', 'michelle rodriguez'));
        $this->addDocument(array('Сэм Уортингтон', 'Sam Worthington', 'sam worthington'));
        $this->addDocument(array('Антон Чехов', 'anton chekhov'));
        $this->addDocument(array('Дж. Дж. Абрамс', 'J. J. Abrams', 'j j abrams'));
        $this->addDocument(array('Чак Лорри', 'Chuck Lorre', 'chuck lorre'));
        $this->addDocument(array('Джонни Галеки', 'Johnny Galecki', 'johnny galecki'));
        $this->addDocument(array('Джим Парсонс', 'Jim Parsons', 'jim parsons'));
        $this->addDocument(array('Кейли Куоукоу', 'Kaley Cuoco', 'Кейли Коукоу', 'Кейли Куоко', 'kaley cuoco'));
        $this->addDocument(array('Саймон Хелберг', 'Simon Helberg', 'simon helberg'));
        $this->addDocument(array('Кунал Наяр', 'Kunal Nayyar', 'kunal nayyar'));
        $this->addDocument(array('Кэнтаро Миура', '三浦 建太郎', 'kentaro miura'));
        $this->addDocument(array('Наохито Такахаси', '高橋 ナオヒト', 'naohito takahashi'));
        $this->addDocument(array('Иммануэл Кант', 'Immanuel Kant', 'Иммануил Кант', 'immanuel kant'));
        $this->addDocument(array('Юрий Лотман', 'juri lotman'));
        $this->addDocument(array('Иезекииль', 'יְחֶזְקֵאל‎', 'ezekiel'));
        $this->addDocument(array('Збых Трофимюк', 'Zbych Trofimiuk', 'zbych trofimiuk'));
        $this->addDocument(array('Гося Пиотровска', 'Gosia Piotrowska', 'gosia piotrowska'));
        $this->addDocument(array('Хизер Митчелл', 'Heather Mitchell', 'heather mitchell'));
        $this->addDocument(array('Джон Ронсон', 'Jon Ronson', 'jon ronson'));
        $this->addDocument(array('Питер Строун', 'Peter Straughan', 'Питер Строхан', 'peter straughan'));
        $this->addDocument(array('Грант Хеслов', 'Grant Heslov', 'grant heslov'));
        $this->addDocument(array('Пол Листер', 'Paul Lister', 'paul lister'));
        $this->addDocument(array('Джордж Клуни', 'George Clooney', 'george clooney'));
        $this->addDocument(array('Юэн Макгрегор', 'Ewan McGregor', 'Эван Макгрегор', 'ewan mcgregor'));
        $this->addDocument(array('Джефф Бриджес', 'Jeff Bridges', 'jeff bridges'));
        $this->addDocument(array('Кевин Спэйси', 'Kevin Spacey', 'kevin spacey'));
        $this->addDocument(array('Гарри Гаррисон', 'Harry Harrison', 'harry harrison'));
        $this->addDocument(array('Даниэль Клугер', 'daniel kluger'));
        $this->addDocument(array('Анатолий Некрасов', 'anatoliy niekrasov'));
        $this->addDocument(array('Гай Ритчи', 'Guy Ritchie', 'guy ritchie'));
        $this->addDocument(array('Джоэл Силвер', 'Joel Silver', 'joel silver'));
        $this->addDocument(array('Роберт Дауни (младший)', 'Robert Downey, Jr.', 'robert downey jr'));
        $this->addDocument(array('Джуд Лоу', 'Jude Law', 'jude law'));
        $this->addDocument(array('Фолькер Шлёндорф', 'Volker Schlöndorff', 'volker schlondorff'));
        $this->addDocument(array('Матьё Каррьер', 'Mathieu Carrière', 'mathieu carriere'));
        $this->addDocument(array('Марко Кройцпайнтнер', 'Marco Kreuzpaintner', 'marco kreuzpaintner'));
        $this->addDocument(array('Роберт Штадлобер', 'Robert Stadlober', 'robert stadlober'));
        $this->addDocument(array('Костя Ульман', 'Kostja Ullmann', 'kostja ullmann'));
        $this->addDocument(array('Алиция Бахледа', 'Alicja Bachleda', 'Алисиа Бачледа', 'Алисия Бахледа', 'Алисья Бачледа', 'Алиция Бахеда', 'alicja bachleda'));
        $this->addDocument(array('Марлон Киттел', 'Marlon Kittel', 'marlon kittel'));
        $this->addDocument(array('Хайнер Каров', 'Heiner Carow', 'heiner carow'));
        $this->addDocument(array('Маттиас Фрайхоф', 'Matthias Freihof', 'matthias freihof'));
        $this->addDocument(array('Дирк Куммер', 'Dirk Kummer', 'dirk kummer'));
        $this->addDocument(array('Александр Тюрин', 'alieksandr tiurin'));
        $this->addDocument(array('Квентин Тарантино', 'Quentin Tarantino', 'quentin tarantino'));
        $this->addDocument(array('Брэд Питт', 'Brad Pitt', 'brad pitt'));
        $this->addDocument(array('Кристоф Вальц', 'Christoph Waltz', 'christoph waltz'));
        $this->addDocument(array('Майкл Фассбендер', 'Michael Fassbender', 'Михаэль Фассбендер', 'michael fassbender'));
        $this->addDocument(array('Элай Рот', 'Eli Roth', 'eli roth'));
        $this->addDocument(array('Даян Крюгер', 'Diane Kruger', 'diane kruger'));
        $this->addDocument(array('Даниэль Брюль', 'Daniel Brühl', 'daniel bruhl'));
        $this->addDocument(array('Тиль Швайгер', 'Til Schweiger', 'til schweiger'));
        $this->addDocument(array('Мелани Лоран', 'Mélanie Laurent', 'melanie laurent'));
        $this->addDocument(array('Лоуренс Бендер', 'Lawrence Bender', 'lawrence bender'));
        $this->addDocument(array('Питер Джексон', 'Peter Jackson', 'peter jackson'));
        $this->addDocument(array('Станислав Лем', 'Stanisław Lem', 'stanislaw lem'));
        $this->addDocument(array('Джон Кристофер', 'John Christopher', 'john christopher'));
        $this->addDocument(array('Линн Окамото', '岡本倫', 'lynn okamoto'));
        $this->addDocument(array('Мамору Канбэ', '神戸 守', 'mamoru kanbe'));
        $this->addDocument(array('Абрахам Меррит', 'Abraham Merritt', 'abraham merritt'));
        $this->addDocument(array('Хаяо Миядзаки', '宮崎 駿', 'hayao miyazaki'));
        $this->addDocument(array('Исао Такахата', '高畑 勲', 'isao takahata'));
        $this->addDocument(array('Тосио Судзуки', '鈴木 敏夫', 'toshio suzuki'));
        $this->addDocument(array('Диана Уинн Джонс', 'Diana Wynne Jones', 'diana wynne jones'));
        $this->addDocument(array('Чингиз Абдуллаев', 'chingiz abdullayev'));
        $this->addDocument(array('Ричард Мид', 'Richard Meade', 'richard meade'));
        $this->addDocument(array('Ева Джонс', 'eva jones'));
        $this->addDocument(array('Такеси Китано', '北野 武', 'takeshi kitano'));
        $this->addDocument(array('Макото Синкай', '新海誠', 'makoto shinkai'));
        $this->addDocument(array('Нил Гейман', 'Neil Gaiman', 'Нейл Гейман', 'neil gaiman'));
        $this->addDocument(array('Мэтью Вон', 'Matthew Vaughn', 'matthew vaughn'));
        $this->addDocument(array('Иэн Маккеллен', 'Ian McKellen', 'Ян Маккеллен', 'ian mckellen'));
        $this->addDocument(array('Чарли Кокс', 'Charlie Cox', 'charlie cox'));
        $this->addDocument(array('Клэр Дэйнс', 'Claire Danes', 'claire danes'));
        $this->addDocument(array('Мишель Файфер', 'Michelle Pfeiffer', 'Мишель Пфайффер', 'michelle pfeiffer'));
        $this->addDocument(array('Роберт Де Ниро', 'Robert De Niro', 'robert de niro'));
        $this->addDocument(array('Марк Стронг', 'Mark Strong', 'mark strong'));
        $this->addDocument(array('Питер О’Тул', 'Peter O’Toole', 'peter o toole'));
        $this->addDocument(array('Дэвид Келли', 'David Kelly', 'david kelly'));
        $this->addDocument(array('Руперт Эверетт', 'Rupert Everett', 'rupert everett'));
        $this->addDocument(array('Генри Селик', 'Henry Selick', 'henry selick'));
        $this->addDocument(array('Кейт Дэвид', 'Keith David', 'keith david'));
        $this->addDocument(array('Тери Хэтчер', 'Teri Hatcher', 'teri hatcher'));
        $this->addDocument(array('Дакота Фаннинг', 'Dakota Fanning', 'dakota fanning'));
        $this->addDocument(array('Тим Бёртон', 'Tim Burton', 'Тим Бартон', 'tim burton'));
        $this->addDocument(array('Дэнни Эльфман', 'Danny Elfman', 'danny elfman'));
        $this->addDocument(array('Дэвид Шор', 'David Shore', 'david shore'));
        $this->addDocument(array('Хью Лори', 'Hugh Laurie', 'hugh laurie'));
        $this->addDocument(array('Отфрид Пройслер', 'Otfried Preußler', 'otfried preussler'));
        $this->addDocument(array('Давид Кросс', 'David Kross', 'david kross'));
        $this->addDocument(array('Фрэнк Герберт', 'Frank Herbert', 'frank herbert'));
        $this->addDocument(array('Джордж Оруэлл', 'George Orwell', 'george orwell'));
        $this->addDocument(array('Масанобу Андо', '安藤政信', 'masanobu ando'));
        $this->addDocument(array('Тацуя Фудзивара', '藤原 竜也', 'tatsuya fujiwara'));
        $this->addDocument(array('Таро Ямамото', '山本 太郎', 'taro yamamoto'));
        $this->addDocument(array('Аки Маэда', '前田亜季', 'aki maeda'));
        $this->addDocument(array('Ко Сибасаки', '柴咲 コウ', 'kou shibasaki'));
        $this->addDocument(array('Тиаки Курияма', '栗山千明', 'chiaki kuriyama'));
        $this->addDocument(array('Кента Фукасаку', '深作 健太', 'kenta fukasaku'));
        $this->addDocument(array('Киндзи Фукасаку', '深作 欣二', 'kinji fukasaku'));
        $this->addDocument(array('Косюн Таками', '高見 広春', 'koushun takami'));
        $this->addDocument(array('Фрэн Уолш', 'Fran Walsh', 'fran walsh'));
        $this->addDocument(array('Стивен Спилберг', 'Steven Spielberg', 'steven spielberg'));
        $this->addDocument(array('Филиппа Боенс', 'Philippa Boyens', 'philippa boyens'));
        $this->addDocument(array('Элис Сиболд', 'Alice Sebold', 'alice sebold'));
        $this->addDocument(array('Сирша Ронан', 'Saoirse Ronan', 'saoirse ronan'));
        $this->addDocument(array('Сьюзан Сэрэндон', 'Susan Sarandon', 'susan sarandon'));
        $this->addDocument(array('Стэнли Туччи', 'Stanley Tucci', 'stanley tucci'));
        $this->addDocument(array('Рэйчел Вайс', 'Rachel Weisz', 'rachel weisz'));
        $this->addDocument(array('Михаэль Ханеке', 'Michael Haneke', 'michael haneke'));
        $this->addDocument(array('Файт Хайдушка', 'Veit Heiduschka', 'veit heiduschka'));
        $this->addDocument(array('Гейл Энн Хёрд', 'Gale Anne Hurd', 'gale anne hurd'));
        $this->addDocument(array('Уильям Уишер-младший', 'William Wisher, Jr.', 'william wisher jr'));
        $this->addDocument(array('Арнольд Шварценеггер', 'Arnold Schwarzenegger', 'arnold schwarzenegger'));
        $this->addDocument(array('Майкл Бин', 'Michael Biehn', 'Майкл Бьен', 'michael biehn'));
        $this->addDocument(array('Линда Хэмилтон', 'Linda Hamilton', 'linda hamilton'));
        $this->addDocument(array('Дэвид Гайлер', 'David Giler', 'david giler'));
        $this->addDocument(array('Уолтер Хилл', 'Walter Hill', 'walter hill'));
        $this->addDocument(array('Кэрри Хенн', 'Carrie Henn', 'carrie henn'));
        $this->addDocument(array('Лэнс Хенриксен', 'Lance Henriksen', 'lance henriksen'));
        $this->addDocument(array('Уильям Хоуп', 'William Hope', 'william hope'));
        $this->addDocument(array('Пол Рейзер', 'Paul Reiser', 'paul reiser'));
        $this->addDocument(array('Эд Харрис', 'Ed Harris', 'ed harris'));
        $this->addDocument(array('Мэри Элизабет Мастрантонио', 'Mary Elizabeth Mastrantonio', 'mary elizabeth mastrantonio'));
        $this->addDocument(array('Кимберли Скотт', 'Kimberly Scott', 'kimberly scott'));
        $this->addDocument(array('Лео Бурместер', 'Leo Burmester', 'leo burmester'));
        $this->addDocument(array('Марио Кассар', 'Mario Kassar', 'mario kassar'));
        $this->addDocument(array('Эдвард Фёрлонг', 'Edward Furlong', 'edward furlong'));
        $this->addDocument(array('Роберт Патрик', 'Robert Patrick', 'robert patrick'));
        $this->addDocument(array('Дэнни Кэннон', 'Danny Cannon', 'danny cannon'));
        $this->addDocument(array('Майкл Де Люка', 'Michael De Luca', 'michael de luca'));
        $this->addDocument(array('Стивен де Суза', 'Steven E. de Souza', 'steven e de souza'));
        $this->addDocument(array('Сильвестр Сталлоне', 'Sylvester Stallone', 'sylvester stallone'));
        $this->addDocument(array('Роб Шнайдер', 'Rob Schneider', 'rob schneider'));
        $this->addDocument(array('Макс фон Сюдов', 'Max von Sydow', 'max von sydow'));
        $this->addDocument(array('Лен Уайзмэн', 'Len Wiseman', 'len wiseman'));
        $this->addDocument(array('Марк Бомбэк', 'Mark Bomback', 'mark bomback'));
        $this->addDocument(array('Брюс Уиллис', 'Bruce Willis', 'bruce willis'));
        $this->addDocument(array('Джастин Лонг', 'Justin Long', 'justin long'));
        $this->addDocument(array('Тимоти Олифант', 'Timothy Olyphant', 'timothy olyphant'));
        $this->addDocument(array('Мэри Элизабет Уинстед', 'Mary Elizabeth Winstead', 'mary elizabeth winstead'));
        $this->addDocument(array('Кевин Смит', 'Kevin Smith', 'kevin smith'));
        $this->addDocument(array('Ли Ань', '李安', 'Энг Ли', 'ang lee'));
        $this->addDocument(array('Ави Арад', 'Avi Arad', 'avi arad'));
        $this->addDocument(array('Стэн Ли', 'Stan Lee', 'stan lee'));
        $this->addDocument(array('Джеймс Шамус', 'James Schamus', 'james schamus'));
        $this->addDocument(array('Майкл Франс', 'Michael France', 'michael france'));
        $this->addDocument(array('Джек Кирби', 'Jack Kirby', 'jack kirby'));
        $this->addDocument(array('Эрик Бана', 'Eric Bana', 'eric bana'));
        $this->addDocument(array('Дженнифер Коннелли', 'Jennifer Connelly', 'jennifer connelly'));
        $this->addDocument(array('Майкл Бэй', 'Michael Bay', 'michael bay'));
        $this->addDocument(array('Джерри Брукхаймер', 'Jerry Bruckheimer', 'jerry bruckheimer'));
        $this->addDocument(array('Джонатан Хенсли', 'Jonathan Hensleigh', 'jonathan hensleigh'));
        $this->addDocument(array('Билли Боб Торнтон', 'Billy Bob Thornton', 'billy bob thornton'));
        $this->addDocument(array('Бен Аффлек', 'Ben Affleck', 'ben affleck'));
        $this->addDocument(array('Лив Тайлер', 'Liv Tyler', 'liv tyler'));
        $this->addDocument(array('Стив Бушеми', 'Steve Buscemi', 'steve buscemi'));
        $this->addDocument(array('Майкл Кларк Дункан', 'Michael Clarke Duncan', 'michael clarke duncan'));
        $this->addDocument(array('Уилл Паттон', 'Will Patton', 'will patton'));
        $this->addDocument(array('Томас Джейн', 'Thomas Jane', 'thomas jane'));
        $this->addDocument(array('Джон Траволта', 'John Travolta', 'john travolta'));
        $this->addDocument(array('Бен Фостер', 'Ben Foster', 'ben foster'));
        $this->addDocument(array('Билл Дюк', 'Bill Duke', 'bill duke'));
        $this->addDocument(array('Джон Мактирнан', 'John McTiernan', 'john mctiernan'));
        $this->addDocument(array('Лоуренс Гордон', 'Lawrence Gordon', 'lawrence gordon'));
        $this->addDocument(array('Джон Дэвис', 'John Davis', 'john davis'));
        $this->addDocument(array('Джим Томас', 'Jim Thomas', 'jim thomas'));
        $this->addDocument(array('Джон Томас', 'John Thomas', 'john thomas'));
        $this->addDocument(array('Кевин Питер Холл', 'Kevin Peter Hall', 'kevin peter hall'));
        $this->addDocument(array('Роберт Родригес', 'Robert Rodriguez', 'robert rodriguez'));
        $this->addDocument(array('Элизабет Авеллан', 'Elizabeth Avellán', 'elizabeth avellan'));
        $this->addDocument(array('Роуз Макгоуэн', 'Rose McGowan', 'rose mcgowan'));
        $this->addDocument(array('Джош Бролин', 'Josh Brolin', 'josh brolin'));
        $this->addDocument(array('Мэрли Шелтон', 'Marley Shelton', 'marley shelton'));
        $this->addDocument(array('Курт Рассел', 'Kurt Russell', 'kurt russell'));
        $this->addDocument(array('Розарио Доусон', 'Rosario Dawson', 'rosario dawson'));
        $this->addDocument(array('Барри Зонненфельд', 'Barry Sonnenfeld', 'barry sonnenfeld'));
        $this->addDocument(array('Джеффри Прайс', 'Jeffrey Price', 'jeffrey price'));
        $this->addDocument(array('Питер С. Симэн', 'Peter S. Seaman', 'peter s seaman'));
        $this->addDocument(array('Уилл Смит', 'Will Smith', 'will smith'));
        $this->addDocument(array('Кевин Клайн', 'Kevin Kline', 'kevin kline'));
        $this->addDocument(array('Кеннет Брана', 'Kenneth Branagh', 'kenneth branagh'));
        $this->addDocument(array('Сальма Хаек', 'Salma Hayek', 'Сальма Хайек', 'salma hayek'));
        $this->addDocument(array('М. Эммет Уолш', 'M. Emmet Walsh', 'm emmet walsh'));
        $this->addDocument(array('Бай Лин', '白灵', 'bai ling'));
        $this->addDocument(array('Ридли Скотт', 'Ridley Scott', 'ridley scott'));
        $this->addDocument(array('Дэн О’Бэннон', 'Dan O’Bannon', 'dan obannon'));
        $this->addDocument(array('Рональд Шусетт', 'Ronald Shusett', 'ronald shusett'));
        $this->addDocument(array('Том Скерритт', 'Tom Skerritt', 'tom skerritt'));
        $this->addDocument(array('Гарри Дин Стэнтон', 'Harry Dean Stanton', 'harry dean stanton'));
        $this->addDocument(array('Вероника Картрайт', 'Veronica Cartwright', 'veronica cartwright'));
        $this->addDocument(array('Джон Хёрт', 'John Hurt', 'john hurt'));
        $this->addDocument(array('Иэн Холм', 'Ian Holm', 'ian holm'));
        $this->addDocument(array('Яфет Котто', 'Yaphet Kotto', 'yaphet kotto'));
        $this->addDocument(array('Филипп К. Дик', 'Philip K. Dick', 'philip k dick'));
        $this->addDocument(array('Харрисон Форд', 'Harrison Ford', 'harrison ford'));
        $this->addDocument(array('Рутгер Хауэр', 'Rutger Hauer', 'rutger hauer'));
        $this->addDocument(array('Шон Янг', 'Sean Young', 'sean young'));
        $this->addDocument(array('Дэрил Ханна', 'Daryl Hannah', 'daryl hannah'));
        $this->addDocument(array('Ума Турман', 'Uma Thurman', 'uma thurman'));
        $this->addDocument(array('Люси Лью', 'Lucy Liu', 'lucy liu'));
        $this->addDocument(array('Жули Драйфус', 'Julie Dreyfus', 'julie dreyfus'));
        $this->addDocument(array('Майкл Мэдсен', 'Michael Madsen', 'michael madsen'));
        $this->addDocument(array('Вивика А. Фокс', 'Vivica A. Fox', 'vivica a fox'));
        $this->addDocument(array('Дэвид Кэррадин', 'David Carradine', 'Дэвид Кэррадайн', 'david carradine'));
        $this->addDocument(array('Стивен Фрай', 'Stephen Fry', 'stephen fry'));
        $this->addDocument(array('Эмма Томпсон', 'Emma Thompson', 'emma thompson'));
        $this->addDocument(array('Имельда Стонтон', 'Imelda Staunton', 'imelda staunton'));
        $this->addDocument(array('Пол Томас Андерсон', 'Paul Thomas Anderson', 'paul thomas anderson'));
        $this->addDocument(array('Джон К. Рейлли', 'John C. Reilly', 'john c reilly'));
        $this->addDocument(array('Том Круз', 'Tom Cruise', 'tom cruise'));
        $this->addDocument(array('Джулианн Мур', 'Julianne Moore', 'julianne moore'));
        $this->addDocument(array('Эйприл Грейс', 'April Grace', 'april grace'));
        $this->addDocument(array('Луис Гузман', 'Luis Guzmán', 'luis guzman'));
        $this->addDocument(array('Филип Бэйкер Холл', 'Philip Baker Hall', 'philip baker hall'));
        $this->addDocument(array('Альфред Молина', 'Alfred Molina', 'alfred molina'));
        $this->addDocument(array('Марк Уолберг', 'Mark Wahlberg', 'mark wahlberg'));
        $this->addDocument(array('Джо Данте', 'Joe Dante', 'joe dante'));
        $this->addDocument(array('Крис Коламбус', 'Chris Columbus', 'chris columbus'));
        $this->addDocument(array('Зак Гэллиган', 'Zach Galligan', 'zach galligan'));
        $this->addDocument(array('Майкл Уинслоу', 'Michael Winslow', 'michael winslow'));
        $this->addDocument(array('Тарсем Сингх', 'Tarsem Singh', 'tarsem singh'));
        $this->addDocument(array('Ли Пэйс', 'Lee Pace', 'lee pace'));
        $this->addDocument(array('Джастин Уэдделл', 'Justine Waddell', 'justine waddell'));
        $this->addDocument(array('Катинка Унтару', 'Catinca Untaru', 'catinca untaru'));
        $this->addDocument(array('Джеймс Белуши', 'James Belushi', 'james belushi'));
        $this->addDocument(array('Питер Бойл', 'Peter Boyle', 'peter boyle'));
        $this->addDocument(array('Эд О’Росс', 'Ed O’Ross', 'ed oross'));
        $this->addDocument(array('Лоуренс Фишбёрн', 'Laurence Fishburne', 'Лоуренс Фишборн', 'laurence fishburne'));
        $this->addDocument(array('Джим Джармуш', 'Jim Jarmusch', 'jim jarmusch'));
        $this->addDocument(array('Джонни Депп', 'Johnny Depp', 'johnny depp'));
        $this->addDocument(array('Гари Фармер', 'Gary Farmer', 'gary farmer'));
        $this->addDocument(array('Игги Поп', 'Iggy Pop', 'iggy pop'));
        $this->addDocument(array('Криспин Гловер', 'Crispin Glover', 'crispin glover'));
        $this->addDocument(array('Майкл Уинкотт', 'Michael Wincott', 'michael wincott'));
        $this->addDocument(array('Роберт Митчем', 'Robert Mitchum', 'robert mitchum'));
        $this->addDocument(array('Керри Конран', 'Kerry Conran', 'kerry conran'));
        $this->addDocument(array('Джон Анвет', 'Jon Avnet', 'jon avnet'));
        $this->addDocument(array('Сэди Фрост', 'Sadie Frost', 'sadie frost'));
        $this->addDocument(array('Гвинет Пэлтроу', 'Gwyneth Paltrow', 'gwyneth paltrow'));
        $this->addDocument(array('Джованни Рибизи', 'Giovanni Ribisi', 'giovanni ribisi'));
        $this->addDocument(array('Майкл Гэмбон', 'Michael Gambon', 'michael gambon'));
        $this->addDocument(array('Омид Джалили', 'Omid Djalili', 'omid djalili'));
        $this->addDocument(array('Лоуренс Оливье', 'Laurence Olivier', 'laurence olivier'));
        $this->addDocument(array('Анджелина Джоли', 'Angelina Jolie', 'angelina jolie'));
        $this->addDocument(array('Чарльз Гордон', 'Charles Gordon', 'charles gordon'));
        $this->addDocument(array('Алан Рикман', 'Alan Rickman', 'alan rickman'));
        $this->addDocument(array('Ренни Харлин', 'Renny Harlin', 'renny harlin'));
        $this->addDocument(array('Ллойд Левин', 'Lloyd Levin', 'lloyd levin'));
        $this->addDocument(array('Роджер Эвери', 'Roger Avary', 'roger avary'));
        $this->addDocument(array('Сэмюэл Л. Джексон', 'Samuel L. Jackson', 'samuel l jackson'));
        $this->addDocument(array('Харви Кейтель', 'Harvey Keitel', 'harvey keitel'));
        $this->addDocument(array('Тим Рот', 'Tim Roth', 'tim roth'));
        $this->addDocument(array('Эрик Штольц', 'Eric Stoltz', 'eric stoltz'));
        $this->addDocument(array('Джейсон Флеминг', 'Jason Flemyng', 'jason flemyng'));
        $this->addDocument(array('Декстер Флетчер', 'Dexter Fletcher', 'dexter fletcher'));
        $this->addDocument(array('Ник Моран', 'Nick Moran', 'nick moran'));
        $this->addDocument(array('Джейсон Стейтем', 'Jason Statham', 'Джейсон Стэтхэм', 'Джейсон Стэтэм', 'jason statham'));
        $this->addDocument(array('Стинг', 'Sting', 'sting'));
        $this->addDocument(array('Винни Джонс', 'Vinnie Jones', 'vinnie jones'));
        $this->addDocument(array('Бенисио дель Торо', 'Benicio del Toro', 'benicio del toro'));
        $this->addDocument(array('Ян де Бонт', 'Jan de Bont', 'jan de bont'));
        $this->addDocument(array('Джеймс Мерендино', 'James Merendino', 'james merendino'));
        $this->addDocument(array('Джеймс Дюваль', 'James Duval', 'james duval'));
        $this->addDocument(array('Мэттью Лиллард', 'Matthew Lillard', 'matthew lillard'));
        $this->addDocument(array('Майкл Империоли', 'Michael Imperioli', 'michael imperioli'));
        $this->addDocument(array('Ричард Чемберлен', 'Richard Chamberlain', 'richard chamberlain'));
        $this->addDocument(array('Джон Рис-Дэвис', 'John Rhys-Davies', 'john rhys davies'));
        $this->addDocument(array('Тосиро Мифунэ', '三船 敏郎', 'toshiro mifune'));
        $this->addDocument(array('Акира Куросава', '黒澤 明', 'akira kurosawa'));
        $this->addDocument(array('Такаси Симура', '志村 喬', 'takashi shimura'));
        $this->addDocument(array('Линда Вулвёртон', 'Linda Woolverton', 'linda woolverton'));
        $this->addDocument(array('Льюис Кэрролл', 'Lewis Carroll', 'lewis carroll'));
        $this->addDocument(array('Мэтт Стоун', 'Matt Stone', 'matt stone'));
        $this->addDocument(array('Трей Паркер', 'Trey Parker', 'trey parker'));
        $this->addDocument(array('Мэтт Грейнинг', 'Matt Groening', 'Мэтт Гроунинг', 'matt groening'));
        $this->addDocument(array('Дэвид Экс. Коэн', 'David X. Cohen', 'david x cohen'));
        $this->addDocument(array('Хэролд Рэмис', 'Harold Ramis', 'Гарольд Рамис', 'harold ramis'));
        $this->addDocument(array('Энди Макдауэлл', 'Andie MacDowell', 'andie macdowell'));
        $this->addDocument(array('Крис Эллиотт', 'Chris Elliott', 'chris elliott'));
        $this->addDocument(array('Браян Дойл-Мюррэй', 'Brian Doyle-Murray', 'brian doyle murray'));
        $this->addDocument(array('Фрэнк Миллер', 'Frank Miller', 'frank miller'));
        $this->addDocument(array('Микки Рурк', 'Mickey Rourke', 'mickey rourke'));
        $this->addDocument(array('Клайв Оуэн', 'Clive Owen', 'clive owen'));
        $this->addDocument(array('Джессика Альба', 'Jessica Alba', 'jessica alba'));
        $this->addDocument(array('Бриттани Мёрфи', 'Brittany Murphy', 'brittany murphy'));
        $this->addDocument(array('Элайджа Вуд', 'Elijah Wood', 'elijah wood'));
        $this->addDocument(array('Уолтер Ф. Паркс', 'Walter F. Parkes', 'walter f parkes'));
        $this->addDocument(array('Лори Макдональд', 'Laurie MacDonald', 'laurie macdonald'));
        $this->addDocument(array('Томми Ли Джонс', 'Tommy Lee Jones', 'tommy lee jones'));
        $this->addDocument(array('Линда Фиорентино', 'Linda Fiorentino', 'linda fiorentino'));
        $this->addDocument(array('Винсент Д’Онофрио', 'Vincent D’Onofrio', 'vincent donofrio'));
        $this->addDocument(array('Роланд Эммерих', 'Roland Emmerich', 'roland emmerich'));
        $this->addDocument(array('Элисон Андерс', 'Allison Anders', 'allison anders'));
        $this->addDocument(array('Александр Рокуэлл', 'Alexandre Rockwell', 'alexandre rockwell'));
        $this->addDocument(array('Мадонна', 'Madonna', 'madonna'));
        $this->addDocument(array('Валерия Голино', 'Valeria Golino', 'valeria golino'));
        $this->addDocument(array('Антонио Бандерас', 'Antonio Banderas', 'antonio banderas'));
        $this->addDocument(array('Люк Бессон', 'Luc Besson', 'luc besson'));
        $this->addDocument(array('Патрис Ледо', 'Patrice Ledoux', 'patrice ledoux'));
        $this->addDocument(array('Гари Олдмэн', 'Gary Oldman', 'gary oldman'));
        $this->addDocument(array('Милла Ёвович', 'Milla Jovovich', 'Милла Йовович', 'milla jovovich'));
        $this->addDocument(array('Джош Хартнетт', 'Josh Hartnett', 'josh hartnett'));
        $this->addDocument(array('Морган Фримэн', 'Morgan Freeman', 'morgan freeman'));
        $this->addDocument(array('Бен Кингсли', 'Ben Kingsley', 'ben kingsley'));
        $this->addDocument(array('Эмиль Хирш', 'Emile Hirsch', 'emile hirsch'));
        $this->addDocument(array('Ольга Курылэнко', 'Olga Kurylenko', 'Ольга Куриленко', 'olga kurylenko'));
        $this->addDocument(array('Рэнди Квэйд', 'Randy Quaid', 'randy quaid'));
        $this->addDocument(array('Хит Леджер', 'Heath Ledger', 'heath ledger'));
        $this->addDocument(array('Джейк Джилленхал', 'Jake Gyllenhaal', 'jake gyllenhaal'));
        $this->addDocument(array('Энн Хэтэвэй', 'Anne Hathaway', 'anne hathaway'));
        $this->addDocument(array('Миа Васиковска', 'Mia Wasikowska', 'mia wasikowska'));
        $this->addDocument(array('Хелена Бонэм Картер', 'Helena Bonham Carter', 'helena bonham carter'));
        $this->addDocument(array('Кристофер Ламбер', 'Christopher Lambert', 'Кристофер Ламберт', 'christopher lambert'));
        $this->addDocument(array('Шон Коннери', 'Sean Connery', 'sean connery'));
        $this->addDocument(array('Гор Вербински', 'Gore Verbinski', 'gore verbinski'));
        $this->addDocument(array('Тед Эллиотт', 'Ted Elliott', 'ted elliott'));
        $this->addDocument(array('Терри Россио', 'Terry Rossio', 'terry rossio'));
        $this->addDocument(array('Орландо Блум', 'Orlando Bloom', 'orlando bloom'));
        $this->addDocument(array('Кира Найтли', 'Keira Knightley', 'keira knightley'));
        $this->addDocument(array('Джеффри Раш', 'Geoffrey Rush', 'geoffrey rush'));
        $this->addDocument(array('Джонатан Прайс', 'Jonathan Pryce', 'jonathan pryce'));
        $this->addDocument(array('Дж. Р. Р. Толкин', 'J. R. R. Tolkien', 'Дж. Р. Р. Толкиен', 'j r r tolkien'));
        $this->addDocument(array('Барри М. Осборн', 'Barrie M. Osborne', 'barrie m osborne'));
        $this->addDocument(array('Шон Астин', 'Sean Astin', 'sean astin'));
        $this->addDocument(array('Вигго Мортенсен', 'Viggo Mortensen', 'viggo mortensen'));
        $this->addDocument(array('Шон Бин', 'Sean Bean', 'sean bean'));
        $this->addDocument(array('Кейт Бланшетт', 'Cate Blanchett', 'cate blanchett'));
        $this->addDocument(array('Энди Серкис', 'Andy Serkis', 'andy serkis'));
        $this->addDocument(array('Кристофер Ли', 'Christopher Lee', 'christopher lee'));
        $this->addDocument(array('Хьюго Уивинг', 'Hugo Weaving', 'hugo weaving'));
        $this->addDocument(array('Бернард Хилл', 'Bernard Hill', 'bernard hill'));
        $this->addDocument(array('Дэвид Уэнхэм', 'David Wenham', 'Дэвид Венхам', 'david wenham'));
        $this->addDocument(array('Брэд Дуриф', 'Brad Dourif', 'brad dourif'));
        $this->addDocument(array('Карлос Галлардо', 'Carlos Gallardo', 'carlos gallardo'));
        $this->addDocument(array('Пит Доктер', 'Pete Docter', 'pete docter'));
        $this->addDocument(array('Ли Анкрич', 'Lee Unkrich', 'lee unkrich'));
        $this->addDocument(array('Дэвид Сильверман', 'David Silverman', 'david silverman'));
        $this->addDocument(array('Дарла К. Андерсон', 'Darla K. Anderson', 'darla k anderson'));
        $this->addDocument(array('Джон Лассетер', 'John Lasseter', 'john lasseter'));
        $this->addDocument(array('Эндрю Стэнтон', 'Andrew Stanton', 'andrew stanton'));
        $this->addDocument(array('Фрэнк Дарабонт', 'Frank Darabont', 'frank darabont'));
        $this->addDocument(array('Стивен Кинг', 'Stephen King', 'stephen king'));
        $this->addDocument(array('Том Хэнкс', 'Tom Hanks', 'tom hanks'));
        $this->addDocument(array('Джеймс Кромвелл', 'James Cromwell', 'james cromwell'));
        $this->addDocument(array('Майкл Джетер', 'Michael Jeter', 'michael jeter'));
        $this->addDocument(array('Сэм Рокуэлл', 'Sam Rockwell', 'sam rockwell'));
        $this->addDocument(array('Труди Стайлер', 'Trudie Styler', 'trudie styler'));
        $this->addDocument(array('Мишель Гондри', 'Michel Gondry', 'michel gondry'));
        $this->addDocument(array('Стив Голин', 'Steve Golin', 'steve golin'));
        $this->addDocument(array('Чарли Кауфман', 'Charlie Kaufman', 'charlie kaufman'));
        $this->addDocument(array('Джим Кэрри', 'Jim Carrey', 'Джим Керри', 'jim carrey'));
        $this->addDocument(array('Кейт Уинслет', 'Kate Winslet', 'kate winslet'));
        $this->addDocument(array('Джордж Лукас', 'George Lucas', 'george lucas'));
        $this->addDocument(array('Гари Кёрц', 'Gary Kurtz', 'gary kurtz'));
        $this->addDocument(array('Рик Маккаллум', 'Rick McCallum', 'rick mccallum'));
        $this->addDocument(array('Марк Хэмилл', 'Mark Hamill', 'mark hamill'));
        $this->addDocument(array('Кэрри Фишер', 'Carrie Fisher', 'carrie fisher'));
        $this->addDocument(array('Питер Кашинг', 'Peter Cushing', 'peter cushing'));
        $this->addDocument(array('Алек Гиннесс', 'Alec Guinness', 'alec guinness'));
        $this->addDocument(array('Энтони Дэниэлс', 'Anthony Daniels', 'anthony daniels'));
        $this->addDocument(array('Кенни Бэйкер', 'Kenny Baker', 'kenny baker'));
        $this->addDocument(array('Питер Мэйхью', 'Peter Mayhew', 'peter mayhew'));
        $this->addDocument(array('Лиам Нисон', 'Liam Neeson', 'liam neeson'));
        $this->addDocument(array('Натали Портман', 'Natalie Portman', 'natalie portman'));
        $this->addDocument(array('Джейк Ллойд', 'Jake Lloyd', 'jake lloyd'));
        $this->addDocument(array('Иэн Макдёрмид', 'Ian McDiarmid', 'ian mcdiarmid'));
        $this->addDocument(array('Хэйден Кристенсен', 'Hayden Christensen', 'hayden christensen'));
        $this->addDocument(array('Фрэнк Оз', 'Frank Oz', 'frank oz'));
        $this->addDocument(array('Ирвин Кёршнер', 'Irvin Kershner', 'irvin kershner'));
        $this->addDocument(array('Ли Брэкетт', 'Leigh Brackett', 'leigh brackett'));
        $this->addDocument(array('Лоуренс Касдан', 'Lawrence Kasdan', 'lawrence kasdan'));
        $this->addDocument(array('Билли Ди Уильямс', 'Billy Dee Williams', 'billy dee williams'));
        $this->addDocument(array('Дэвид Проус', 'David Prowse', 'david prowse'));
        $this->addDocument(array('Жан Рено', 'Jean Reno', 'jean reno'));
        $this->addDocument(array('Дэнни Аелло', 'Danny Aiello', 'Дэнни Айелло', 'danny aiello'));
        $this->addDocument(array('Горо Миядзаки', '宮崎 吾朗', 'goro miyazaki'));
        $this->addDocument(array('Урсула К. Ле Гуин', 'Ursula K. Le Guin', 'ursula k le guin'));
        $this->addDocument(array('Дэнни Трехо', 'Danny Trejo', 'danny trejo'));
        $this->addDocument(array('Чич Марин', 'Cheech Marin', 'cheech marin'));
        $this->addDocument(array('Хулио Оскар Мечосо', 'Julio Oscar Mechoso', 'julio oscar mechoso'));
        $this->addDocument(array('Тито Ларрива', 'Tito Larriva', 'tito larriva'));
        $this->addDocument(array('Рубен Блейдс', 'Rubén Blades', 'ruben blades'));
        $this->addDocument(array('Уиллем Дэфо', 'Willem Dafoe', 'willem dafoe'));
        $this->addDocument(array('Джон Огаст', 'John August', 'john august'));
        $this->addDocument(array('Кэролайн Томпсон', 'Caroline Thompson', 'caroline thompson'));
        $this->addDocument(array('Скотт Рудин', 'Scott Rudin', 'scott rudin'));
        $this->addDocument(array('Адам Шрёдер', 'Adam Schroeder', 'adam schroeder'));
        $this->addDocument(array('Фрэнсис Форд Коппола', 'Francis Ford Coppola', 'francis ford coppola'));
        $this->addDocument(array('Ларри Дж. Франко', 'Larry J. Franco', 'larry j franco'));
        $this->addDocument(array('Уошингтон Ирвинг', 'Washington Irving', 'Вашингтон Ирвинг', 'washington irving'));
        $this->addDocument(array('Эндрю Кевин Уолкер', 'Andrew Kevin Walker', 'andrew kevin walker'));
        $this->addDocument(array('Кристофер Уокен', 'Christopher Walken', 'christopher walken'));
        $this->addDocument(array('Кристина Риччи', 'Christina Ricci', 'christina ricci'));
        $this->addDocument(array('Миранда Ричардсон', 'Miranda Richardson', 'miranda richardson'));
        $this->addDocument(array('Джеффри Джонс', 'Jeffrey Jones', 'jeffrey jones'));
        $this->addDocument(array('Ричард Гриффитс', 'Richard Griffiths', 'richard griffiths'));
        $this->addDocument(array('Майкл Гью', 'Michael Gough', 'Майкл Гуг', 'michael gough'));
        $this->addDocument(array('Питер Финч', 'Peter Finch', 'peter finch'));
        $this->addDocument(array('Чарльз Бронсон', 'Charles Bronson', 'charles bronson'));
        $this->addDocument(array('Джеймс Вудс', 'James Woods', 'james woods'));
        $this->addDocument(array('Роберт Лоджиа', 'Robert Loggia', 'robert loggia'));
        $this->addDocument(array('Сильвия Сидни', 'Sylvia Sidney', 'sylvia sidney'));
        $this->addDocument(array('Хироюки Морита', '森田 宏幸', 'hiroyuki morita'));
        $this->addDocument(array('Аой Хиираги', '柊 あおい', 'aoi hiiragi'));
        $this->addDocument(array('Рэйко Ёсида', '吉田 玲子', 'reiko yoshida'));
        $this->addDocument(array('Стивен Лэнг', 'Stephen Lang', 'stephen lang'));
        $this->addDocument(array('Ёсиаки Кавадзири', '川尻 善昭', 'yoshiaki kawajiri'));
        $this->addDocument(array('Морио Асака', '浅香 守生', 'morio asaka'));
        $this->addDocument(array('Тецуро Араки', '荒木 哲郎', 'tetsuro araki'));
        $this->addDocument(array('Ацуко Исидзука', 'いしづか あつこ', 'atsuko ishizuka'));
        $this->addDocument(array('Рюноскэ Акутагава', '芥川 龍之介', 'ryunosuke akutagawa'));
        $this->addDocument(array('Осаму Дадзай', '太宰 治', 'osamu dazai'));
        $this->addDocument(array('Нацумэ Сосэки', '夏目 漱石', 'natsume soseki'));
        $this->addDocument(array('Сюнгику Накамура', '中村 春菊', 'shungiku nakamura'));
        $this->addDocument(array('Тиаки Кон', '今 千秋', 'chiaki kon'));
        $this->addDocument(array('Павел Санаев', 'paviel sanayev'));
        $this->addDocument(array('Лу Е', '娄烨', 'Лоу Йе', 'lou ye'));
        $this->addDocument(array('Лариса Чагровская', 'Лариса Чагровська', 'larysa chahrovska'));
        $this->addDocument(array('Наталка Шевченко', 'natalka shevchenko'));
        $this->addDocument(array('Николай Басов', 'nikolay basov'));
        $this->addDocument(array('Кентаро Катаяма', '片山憲太郎', 'kentaro katayama'));
        $this->addDocument(array('Ямато Ямамото', '山本ヤマト', 'yamato yamamoto'));
        $this->addDocument(array('Хироюки Ёсино', '吉野弘幸', 'hiroyuki yoshino'));
        $this->addDocument(array('Ник Перумов', 'nick perumov'));
        $this->addDocument(array('Полина Каминская', 'polina kaminskaya'));
        $this->addDocument(array('Клиффорд Саймак', 'Clifford Simak', 'clifford simak'));
        $this->addDocument(array('Том Тыквер', 'Tom Tykwer', 'tom tykwer'));
        $this->addDocument(array('Франка Потенте', 'Franka Potente', 'franka potente'));
        $this->addDocument(array('Бенно Фюрманн', 'Benno Fürmann', 'benno furmann'));
        $this->addDocument(array('Мориц Блайбтрой', 'Moritz Bleibtreu', 'moritz bleibtreu'));
        $this->addDocument(array('Майкл Айронсайд', 'Michael Ironside', 'michael ironside'));
        $this->addDocument(array('Дэймон Вэенс', 'Damon Wayans', 'damon wayans'));
        $this->addDocument(array('Тацуя Исихара', '石原立也', 'tatsuya ishihara'));
        $this->addDocument(array('Фатих Акын', 'Fatih Akın', 'fatih akin'));
        $this->addDocument(array('Серджо Леоне', 'Sergio Leone', 'sergio leone'));
        $this->addDocument(array('Клинт Иствуд', 'Clint Eastwood', 'clint eastwood'));
        $this->addDocument(array('Арнон Милчан', 'ארנון מילצ\'ן', 'arnon milchan'));
        $this->addDocument(array('Джо Пеши', 'Joe Pesci', 'joe pesci'));
        $this->addDocument(array('Ричард Келли', 'Richard Kelly', 'richard kelly'));
        $this->addDocument(array('Кэмерон Диас', 'Cameron Diaz', 'cameron diaz'));
        $this->addDocument(array('Джеймс Марсден', 'James Marsden', 'james marsden'));
        $this->addDocument(array('Фрэнк Ланджелла', 'Frank Langella', 'frank langella'));
        $this->addDocument(array('Боб Гейл', 'Bob Gale', 'bob gale'));
        $this->addDocument(array('Эми Смарт', 'Amy Smart', 'amy smart'));
        $this->addDocument(array('Кристофер Ллойд', 'Christopher Lloyd', 'christopher lloyd'));
        $this->addDocument(array('Майкл Дж. Фокс', 'Michael J. Fox', 'michael j fox'));
        $this->addDocument(array('Роберт Земекис', 'Robert Zemeckis', 'robert zemeckis'));
        $this->addDocument(array('Кэтлин Кеннеди', 'Kathleen Kennedy', 'kathleen kennedy'));
        $this->addDocument(array('Марк Гордон', 'Mark Gordon', 'mark gordon'));
        $this->addDocument(array('Гаральд Клосер', 'Harald Kloser', 'harald kloser'));
        $this->addDocument(array('Томас Маккарти', 'Thomas McCarthy', 'thomas mccarthy'));
        $this->addDocument(array('Джон Кьюсак', 'John Cusack', 'john cusack'));
        $this->addDocument(array('Лиам Джеймс', 'Liam James', 'liam james'));
        $this->addDocument(array('Беатрис Розен', 'Beatrice Rosen', 'beatrice rosen'));
        $this->addDocument(array('Оливер Плэтт', 'Oliver Platt', 'oliver platt'));
        $this->addDocument(array('Тэнди Ньютон', 'Thandie Newton', 'thandie newton'));
        $this->addDocument(array('Чарльз Ровен', 'Charles Roven', 'charles roven'));
        $this->addDocument(array('Кристиан Бэйл', 'Christian Bale', 'christian bale'));
        $this->addDocument(array('Аарон Экхарт', 'Aaron Eckhart', 'aaron eckhart'));
        $this->addDocument(array('Мэгги Джилленхал', 'Maggie Gyllenhaal', 'maggie gyllenhaal'));
        $this->addDocument(array('Скип Вудс', 'Skip Woods', 'skip woods'));
        $this->addDocument(array('Джеймс Легрос', 'James LeGros', 'james legros'));
        $this->addDocument(array('Киану Ривз', 'Keanu Reeves', 'keanu reeves'));
        $this->addDocument(array('Джо Пантолиано', 'Joe Pantoliano', 'joe pantoliano'));
        $this->addDocument(array('Гарольд Перрино', 'Harold Perrineau', 'harold perrineau'));
        $this->addDocument(array('Натаниэль Лис', 'Nathaniel Lees', 'nathaniel lees'));
        $this->addDocument(array('Уэсли Снайпс', 'Wesley Snipes', 'wesley snipes'));
        $this->addDocument(array('Ари Фолман', 'ארי פולמן', 'ari folman'));
        $this->addDocument(array('Эндрю Адамсон', 'Andrew Adamson', 'andrew adamson'));
        $this->addDocument(array('Марк Джонсон', 'Mark Johnson', 'mark johnson'));
        $this->addDocument(array('Си. С. Льюис', 'C. S. Lewis', 'c s lewis'));
        $this->addDocument(array('Франц Кафка', 'Franz Kafka', 'franz kafka'));
        $this->addDocument(array('Билл Прэди', 'Bill Prady', 'bill prady'));
        $this->addDocument(array('Роджер Уотерс', 'Roger Waters', 'roger waters'));
        $this->addDocument(array('Ник Мэйсон', 'Nick Mason', 'nick mason'));
        $this->addDocument(array('Дэвид Гилмор', 'David Gilmour', 'david gilmour'));
        $this->addDocument(array('Алан Паркер', 'Alan Parker', 'alan parker'));
        $this->addDocument(array('Форест Уитакер', 'Forest Whitaker', 'forest whitaker'));
        $this->addDocument(array('Джеймс Макэвой', 'James McAvoy', 'james mcavoy'));
        $this->addDocument(array('Виктор Пелевин', 'viktor pielievin'));
        $this->addDocument(array('Терри Гиллиам', 'Terry Gilliam', 'terry gilliam'));
        $this->addDocument(array('Верн Троер', 'Verne Troyer', 'verne troyer'));
        $this->addDocument(array('Колин Фаррелл', 'Colin Farrell', 'colin farrell'));
        $this->addDocument(array('Кобо Абэ', '安部公房', 'kobo abe'));
        $this->addDocument(array('Лена Хеди', 'Lena Headey', 'lena headey'));
        $this->addDocument(array('Доминик Уэст', 'Dominic West', 'dominic west'));
        $this->addDocument(array('Туве Янссон', 'Tove Jansson', 'tove jansson'));
        $this->addDocument(array('Паул Верхувен', 'Paul Verhoeven', 'Пол Верховен', 'paul verhoeven'));
        $this->addDocument(array('Питер Уэллер', 'Peter Weller', 'peter weller'));
        $this->addDocument(array('Ронни Кокс', 'Ronny Cox', 'ronny cox'));
        $this->addDocument(array('Вэйлон Грин', 'Walon Green', 'walon green'));
        $this->addDocument(array('Элизабет Шу', 'Elisabeth Shue', 'elisabeth shue'));
        $this->addDocument(array('Вильям Девэйн', 'William Devane', 'william devane'));
        $this->addDocument(array('Джои Слотник', 'Joey Slotnick', 'joey slotnick'));
        $this->addDocument(array('Ким Диккенс', 'Kim Dickens', 'kim dickens'));
        $this->addDocument(array('Дитер Нолль', 'Dieter Noll', 'dieter noll'));
        $this->addDocument(array('Кристофер Нолан', 'Christopher Nolan', 'christopher nolan'));
        $this->addDocument(array('Сюзанн Тодд', 'Suzanne Todd', 'suzanne todd'));
        $this->addDocument(array('Дженнифер Тодд', 'Jennifer Todd', 'jennifer todd'));
        $this->addDocument(array('Джонатан Нолан', 'Jonathan Nolan', 'jonathan nolan'));
        $this->addDocument(array('Гай Пирс', 'Guy Pearce', 'guy pearce'));
        $this->addDocument(array('Кэрри-Энн Мосс', 'Carrie-Anne Moss', 'carrie anne moss'));
        $this->addDocument(array('Ффф Рар', 'Fff Rar', 'fff rar'));
        $this->addDocument(array('Ральф Файнз', 'Ralph Fiennes', 'Ральф Файнс', 'ralph fiennes'));
        $this->addDocument(array('Дэвид Морс', 'David Morse', 'david morse'));
        $this->addDocument(array('Николь Эванджелин Лилли', 'Nicole Evangeline Lilly', 'nicole evangeline lilly'));
        $this->addDocument(array('Джейн Голдман', 'Jane Goldman', 'jane goldman'));
        $this->addDocument(array('Николас Кэйдж', 'Nicolas Cage', 'nicolas cage'));
        $this->addDocument(array('Элизабет Макговерн', 'Elizabeth McGovern', 'elizabeth mcgovern'));
        $this->addDocument(array('Ксандер Беркли', 'Xander Berkeley', 'xander berkeley'));
        $this->addDocument(array('Браян Кинг', 'Brian King', 'brian king'));
        $this->addDocument(array('Дэнни Гловер', 'Danny Glover', 'danny glover'));
        $this->addDocument(array('Лили Собески', 'Leelee Sobieski', 'leelee sobieski'));
        $this->addDocument(array('Стив Зан', 'Steve Zahn', 'steve zahn'));
        $this->addDocument(array('Джеф Белл', 'Geoff Bell', 'geoff bell'));
        $this->addDocument(array('Ноа Тэйлор', 'Noah Taylor', 'noah taylor'));
        $this->addDocument(array('Армин Мюллер-Шталь', 'Armin Mueller-Stahl', 'armin mueller stahl'));
        $this->addDocument(array('Дженнифер Рубин', 'Jennifer Rubin', 'jennifer rubin'));
        $this->addDocument(array('Брюс Боа', 'Bruce Boa', 'bruce boa'));
        $this->addDocument(array('Рон Уайт', 'Ron White', 'ron white'));
        $this->addDocument(array('Генри Каттнер', 'Henry Kuttner', 'henry kuttner'));
        $this->addDocument(array('К. Л. Мур', 'C. L. Moore', 'c l moore'));
        $this->addDocument(array('Джозеф Хеллер', 'Joseph Heller', 'joseph heller'));
        $this->addDocument(array('Джеймс Фокс', 'James Fox', 'james fox'));
        $this->addDocument(array('Ричард Занук', 'Richard Zanuck', 'richard zanuck'));
        $this->addDocument(array('Мисси Пайл', 'Missi Pyle', 'missi pyle'));
        $this->addDocument(array('Хидэаки Анно', '庵野秀明', 'hideaki anno'));
        $this->addDocument(array('Казуя Цурумаки', '鶴巻 和哉', 'kazuya tsurumaki'));
        $this->addDocument(array('Мицухиса Исикава', '石川 光久', 'mitsuhisa ishikawa'));
        $this->addDocument(array('Хироюки Имаиси', '今石洋之', 'hiroyuki imaishi'));
        $this->addDocument(array('Акиюки Синбо', '新房 昭之', 'akiyuki shinbo'));
        $this->addDocument(array('Джек Николсон', 'Jack Nicholson', 'jack nicholson'));
        $this->addDocument(array('Гленн Клоуз', 'Glenn Close', 'glenn close'));
        $this->addDocument(array('Аннет Бенинг', 'Annette Bening', 'annette bening'));
        $this->addDocument(array('Пирс Броснан', 'Pierce Brosnan', 'pierce brosnan'));
        $this->addDocument(array('Дэнни Девито', 'Danny DeVito', 'Дэнни Де Вито', 'danny devito'));
        $this->addDocument(array('Сара Джессика Паркер', 'Sarah Jessica Parker', 'sarah jessica parker'));
        $this->addDocument(array('Лукас Хаас', 'Lukas Haas', 'lukas haas'));
        $this->addDocument(array('Лиза Мари Смит', 'Lisa Marie Smith', 'lisa marie smith'));
        $this->addDocument(array('Пам Гриер', 'Pam Grier', 'pam grier'));
        $this->addDocument(array('Пол Уинфилд', 'Paul Winfield', 'paul winfield'));
        $this->addDocument(array('Браян Хэйли', 'Brian Haley', 'brian haley'));
        $this->addDocument(array('Джозеф Маэр', 'Joseph Maher', 'joseph maher'));
        $this->addDocument(array('Джон Логан', 'John Logan', 'john logan'));
        $this->addDocument(array('Джейми Кэмпбелл Бауэр', 'Jamie Campbell Bower', 'jamie campbell bower'));
        $this->addDocument(array('Таданобу Асано', '浅野 忠信', 'asano tadanobu'));
        $this->addDocument(array('Казуто Наказава', '中澤 一登', 'kazuto nakazawa'));
        $this->addDocument(array('Минору Нисида', '西田 稔', 'minoru nishida'));
        $this->addDocument(array('Арнольд Копельсон', 'Arnold Kopelson', 'arnold kopelson'));
        $this->addDocument(array('Оливер Стоун', 'Oliver Stone', 'oliver stone'));
        $this->addDocument(array('Джон К. Макгинли', 'John C. McGinley', 'john c mcginley'));
        $this->addDocument(array('Елена Колядина', 'yeliena koliadina'));
        $this->addDocument(array('Дженнифер Билз', 'Jennifer Beals', 'jennifer beals'));
        $this->addDocument(array('Тим Гвини', 'Tim Guinee', 'tim guinee'));
        $this->addDocument(array('Майкл Джексон', 'Michael Jackson', 'michael jackson'));
        $this->addDocument(array('Томас Манн', 'Thomas Mann', 'thomas mann'));
        $this->addDocument(array('Кацуя Кондо', '近藤 勝也', 'katsuya kondo'));
        $this->addDocument(array('Томоми Мотидзуки', '望月 智充', 'tomomi mochizuki'));
        $this->addDocument(array('Ричард Морган', 'Richard K. Morgan', 'richard k morgan'));
        $this->addDocument(array('Говард Лавкрафт', 'H. P. Lovecraft', 'h p lovecraft'));
        $this->addDocument(array('Роман Полански', 'Roman Polanski', 'roman polanski'));
        $this->addDocument(array('Коре Холт', 'Kåre Holt', 'kaare holt'));
        $this->addDocument(array('Рюхеи Мацуда', 'Ryuhei Matsuda', 'ryuhei matsuda'));
        $this->addDocument(array('Сосуке Такаока', '高岡蒼甫', 'sousuke takaoka'));
    }

    public function testEmpty() {
        $this->search("blablabla");
        $this->findNothing();
    }

    public function testTrntn() {
        $this->search("торнтина");
        $this->find("Квентин Тарантино");
        $this->find("Билли Боб Торнтон");

        $this->search("тарантино");
        $this->findOnly("Квентин Тарантино");

        $this->search("торнтон");
        $this->findOnly("Билли Боб Торнтон");
    }

    public function testMiyazaki() {
        $this->search("миядзаки");
        $this->find("Хаяо Миядзаки");
        $this->find("Горо Миядзаки");

        $this->search("хаяо миядзаки");
        $this->findOnly("Хаяо Миядзаки");

        $this->search("горо миядзаки");
        $this->findOnly("Горо Миядзаки");
    }

    public function testDune() {
        $this->search("dune");
        $this->find("Дюна");
        $this->find("Мессия Дюны");
        $this->find("Дети Дюны");
        $this->find("Бог-Император Дюны");
        $this->find("Еретики Дюны");
    }

    public function testZauberberg() {
        $this->search("zauberberg");
        $this->findOnly("Волшебная гора");

        $this->search("волшебная гора");
        $this->findOnly("Волшебная гора");

        $this->search("волшебную гору");
        $this->find("Волшебная гора");
    }

    public function testAkutagawa() {
        $this->search("рюноскэ акутагава");
        $this->findOnly("Рюноскэ Акутагава");

        $this->search("рюноскэ");
        $this->find("Рюноскэ Акутагава");

        $this->search("акутагава");
        $this->find("Рюноскэ Акутагава");

        $this->search("ryunosuke");
        $this->find("Рюноскэ Акутагава");

        $this->search("рюносуке");
        $this->find("Рюноскэ Акутагава");
    }

    public function testCharlie() {
        $this->search("чарли");
        $this->find("Чарли и шоколадная фабрика");
        $this->find("Чарли Кокс");
        $this->find("Чарли Кауфман");
    }

    public function testEarthsea() {
        $this->search("земноморье");
        $this->find("Волшебник Земноморья");
        $this->find("Сказания Земноморья");
        $this->find("Похождения Геда");
    }

    public function testOrwell() {
        $this->search("George Orwell");
        $this->findOnly("Джордж Оруэлл");
    }

    public function testFrequentWords() {
        $this->search("a");
        $this->findNothing();

        $this->search("the");
        $this->findNothing();

        $this->search("and");
        $this->findNothing();

        $this->search("of");
        $this->findNothing();

        $this->search("в");
        $this->findNothing();
    }
}